version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lets_travel
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lets_travel_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/lets_travel
    ports:
      - "3000:3000"
    depends_on:
      - db
  assets:
    build: .
    volumes:
      - .:/lets_travel
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
    command: sh -c "yarn install && yarn build"
volumes:
  pgdata: 