default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: lets_travel
  host: db # Dockerのサービス名
  port: 5432

development:
  <<: *default
  database: lets_travel_development

test:
  <<: *default
  database: lets_travel_test

production:
  <<: *default
  database: lets_travel_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>